#!/bin/bash

# Fonction pour créer un fichier avec commentaire en première ligne
create_file() {
  local filepath=$1
  local comment=$2
  mkdir -p "$(dirname "$filepath")"
  echo "$comment" > "$filepath"
}

# ========== AUTH ==========
create_file "features/auth/components/LoginForm.tsx"           "// Formulaire de connexion"
create_file "features/auth/components/RegisterForm.tsx"        "// Formulaire d'inscription"
create_file "features/auth/components/OTPVerification.tsx"     "// Vérification SMS/Mobile Money"
create_file "features/auth/components/PasswordReset.tsx"       "// Réinitialisation mot de passe"
create_file "features/auth/components/AuthGuard.tsx"           "// HOC pour routes protégées"
create_file "features/auth/hooks/useAuth.ts"                   "// Hook principal d'authentification"
create_file "features/auth/hooks/useOTP.ts"                    "// Gestion OTP"
create_file "features/auth/hooks/usePasswordReset.ts"          "// Reset password flow"
create_file "features/auth/services/auth.api.ts"               "// API calls spécifiques auth"
create_file "features/auth/stores/auth.store.ts"               "// État local auth (Zustand)"
create_file "features/auth/utils/validators.ts"                "// Validation forms auth"
create_file "features/auth/utils/security.ts"                  "// Utilitaires sécurité"
create_file "features/auth/index.ts"                           "// Export contrôlé"

# ========== MARKETPLACE ==========
create_file "features/marketplace/components/search/SearchBar.tsx"          "// Barre de recherche intelligente"
create_file "features/marketplace/components/search/SearchFilters.tsx"      "// Filtres par catégorie, prix, etc."
create_file "features/marketplace/components/search/SearchSuggestions.tsx"  "// Suggestions en temps réel"
create_file "features/marketplace/components/merchants/MerchantGrid.tsx"    "// Grille des marchands"
create_file "features/marketplace/components/merchants/MerchantCard.tsx"    "// Carte marchand avec rating"
create_file "features/marketplace/components/merchants/MerchantHero.tsx"    "// Bannière promo marchand"
create_file "features/marketplace/components/merchants/MerchantSchedule.tsx" "// Indicateur ouvert/fermé"
create_file "features/marketplace/components/products/ProductCatalog.tsx"   "// Catalogue produits d'un marchand"
create_file "features/marketplace/components/products/ProductCard.tsx"      "// Carte produit avec add to cart"
create_file "features/marketplace/components/products/ProductModal.tsx"     "// Modal détail produit"
create_file "features/marketplace/components/discovery/CategoryCarousel.tsx" "// Carousel catégories"
create_file "features/marketplace/components/discovery/PromoBanners.tsx"    "// Bannières promotions"
create_file "features/marketplace/components/discovery/TrendingMerchants.tsx" "// Marchands tendances"
create_file "features/marketplace/hooks/useSearch.ts"           "// Recherche et filtres"
create_file "features/marketplace/hooks/useMerchants.ts"        "// Gestion données marchands"
create_file "features/marketplace/hooks/useProducts.ts"         "// Gestion produits/catalogue"
create_file "features/marketplace/hooks/useDiscovery.ts"        "// Données découverte (trending, etc.)"
create_file "features/marketplace/services/merchants.api.ts"    "// API marchands"
create_file "features/marketplace/services/products.api.ts"     "// API produits"
create_file "features/marketplace/services/search.api.ts"       "// API recherche"
create_file "features/marketplace/types/merchant.types.ts"      "// Types marketplace (marchands)"
create_file "features/marketplace/types/product.types.ts"       "// Types marketplace (produits)"
create_file "features/marketplace/types/search.types.ts"        "// Types marketplace (recherche)"
create_file "features/marketplace/index.ts"                     "// Export contrôlé"

# ========== ORDERS ==========
create_file "features/orders/components/cart/CartSidebar.tsx"   "// Panier slide-in"
create_file "features/orders/components/cart/CartItem.tsx"      "// Item panier"
create_file "features/orders/components/cart/CartSummary.tsx"   "// Récap panier"
create_file "features/orders/components/checkout/CheckoutStepper.tsx" "// Stepper commande"
create_file "features/orders/components/checkout/DeliveryAddress.tsx" "// Adresse livraison"
create_file "features/orders/components/checkout/TimeSelection.tsx"   "// Choix horaire"
create_file "features/orders/components/checkout/OrderSummary.tsx"    "// Récap avant paiement"
create_file "features/orders/components/tracking/OrderStatusBar.tsx"  "// Barre progression"
create_file "features/orders/components/tracking/LiveTracking.tsx"    "// Carte suivi"
create_file "features/orders/components/tracking/CourierInfo.tsx"     "// Info livreur"
create_file "features/orders/components/tracking/EstimatedTime.tsx"   "// Compte à rebours"
create_file "features/orders/components/history/OrderHistory.tsx"     "// Liste commandes"
create_file "features/orders/components/history/OrderCard.tsx"        "// Carte commande"
create_file "features/orders/components/history/ReorderButton.tsx"    "// Recommander"
create_file "features/orders/components/modals/CustomOrderModal.tsx"  "// Modal commande custom"
create_file "features/orders/components/modals/OrderDetailsModal.tsx" "// Modal détails commande"
create_file "features/orders/hooks/useCart.ts"                "// Gestion panier"
create_file "features/orders/hooks/useCheckout.ts"            "// Checkout"
create_file "features/orders/hooks/useOrderTracking.ts"       "// Tracking commande"
create_file "features/orders/hooks/useOrderHistory.ts"        "// Historique commandes"
create_file "features/orders/hooks/useReorder.ts"             "// Recommande"
create_file "features/orders/stores/cart.store.ts"            "// Store panier"
create_file "features/orders/services/orders.api.ts"          "// API commandes"
create_file "features/orders/services/cart.api.ts"            "// API panier"
create_file "features/orders/services/tracking.api.ts"        "// API tracking"
create_file "features/orders/index.ts"                        "// Export contrôlé"

# ========== PAYMENTS ==========
create_file "features/payments/components/methods/PaymentMethodSelector.tsx" "// Sélecteur méthode"
create_file "features/payments/components/methods/MobileMoneyForm.tsx"      "// Formulaire Mobile Money"
create_file "features/payments/components/methods/CreditCardForm.tsx"       "// Formulaire carte crédit"
create_file "features/payments/components/methods/CashOnDelivery.tsx"       "// Paiement à la livraison"
create_file "features/payments/components/processing/PaymentProcessing.tsx" "// Écran traitement"
create_file "features/payments/components/processing/PaymentSuccess.tsx"    "// Succès"
create_file "features/payments/components/processing/PaymentError.tsx"      "// Erreur"
create_file "features/payments/components/security/SecureBadge.tsx"         "// Badge sécurité"
create_file "features/payments/components/security/EncryptionInfo.tsx"      "// Info chiffrement"
create_file "features/payments/hooks/usePaymentMethods.ts"     "// Liste méthodes paiement"
create_file "features/payments/hooks/usePaymentProcessing.ts"  "// Processing paiement"
create_file "features/payments/hooks/usePaymentSecurity.ts"    "// Sécurité paiement"
create_file "features/payments/services/payment.api.ts"        "// API paiement"
create_file "features/payments/services/mobile-money.api.ts"   "// API Mobile Money"
create_file "features/payments/services/transaction.api.ts"    "// API transaction"
create_file "features/payments/utils/payment-validators.ts"    "// Validation paiement"
create_file "features/payments/utils/encryption.ts"            "// Utilitaires chiffrement"
create_file "features/payments/utils/currency.ts"              "// Conversion devises"
create_file "features/payments/index.ts"                       "// Export contrôlé"

# ========== PROFILE ==========
create_file "features/profile/components/overview/ProfileHeader.tsx" "// Header profil"
create_file "features/profile/components/overview/StatsOverview.tsx" "// Stats commandes"
create_file "features/profile/components/overview/QuickActions.tsx"  "// Actions rapides"
create_file "features/profile/components/preferences/AddressBook.tsx" "// Gestion adresses"
create_file "features/profile/components/preferences/NotificationPrefs.tsx" "// Préférences notifications"
create_file "features/profile/components/preferences/LanguageSelector.tsx" "// Sélecteur langue"
create_file "features/profile/components/loyalty/LoyaltyCard.tsx"    "// Carte fidélité"
create_file "features/profile/components/loyalty/PointsBalance.tsx"  "// Solde points"
create_file "features/profile/components/loyalty/RewardsCatalog.tsx" "// Catalogue récompenses"
create_file "features/profile/components/security/PasswordChange.tsx" "// Changer mdp"
create_file "features/profile/components/security/TwoFactorAuth.tsx" "// 2FA"
create_file "features/profile/components/security/SessionManager.tsx" "// Sessions"
create_file "features/profile/hooks/useProfile.ts"            "// Données profil"
create_file "features/profile/hooks/usePreferences.ts"        "// Préférences"
create_file "features/profile/hooks/useLoyalty.ts"            "// Fidélité"
create_file "features/profile/hooks/useSecurity.ts"           "// Sécurité"
create_file "features/profile/services/profile.api.ts"        "// API profil"
create_file "features/profile/services/preferences.api.ts"    "// API préférences"
create_file "features/profile/services/loyalty.api.ts"        "// API fidélité"
create_file "features/profile/index.ts"                       "// Export contrôlé"

# ========== SUBSCRIPTIONS ==========
create_file "features/subscriptions/components/plans/PlanComparison.tsx" "// Comparatif plans"
create_file "features/subscriptions/components/plans/PlanCard.tsx"      "// Carte plan"
create_file "features/subscriptions/components/plans/FeatureList.tsx"   "// Liste avantages"
create_file "features/subscriptions/components/billing/BillingCycle.tsx" "// Cycle facturation"
create_file "features/subscriptions/components/billing/InvoiceHistory.tsx" "// Historique factures"
create_file "features/subscriptions/components/billing/UpgradeModal.tsx" "// Modal upgrade"
create_file "features/subscriptions/components/benefits/BenefitBadge.tsx" "// Badge avantage"
create_file "features/subscriptions/components/benefits/UsageTracker.tsx" "// Suivi utilisation"
create_file "features/subscriptions/components/benefits/RenewalReminder.tsx" "// Rappel renouvellement"
create_file "features/subscriptions/hooks/useSubscription.ts"   "// Hook abonnement"
create_file "features/subscriptions/hooks/useBilling.ts"        "// Hook facturation"
create_file "features/subscriptions/hooks/useBenefits.ts"       "// Hook avantages"
create_file "features/subscriptions/services/subscription.api.ts" "// API abonnements"
create_file "features/subscriptions/services/billing.api.ts"    "// API facturation"
create_file "features/subscriptions/utils/pricing.ts"           "// Calcul prix"
create_file "features/subscriptions/index.ts"                   "// Export contrôlé"

# ========== PARTNER ONBOARDING ==========
create_file "features/partner-onboarding/components/PartnerTypeSelector.tsx"    "// Choix marchand/livreur"
create_file "features/partner-onboarding/components/MerchantOnboardingForm.tsx" "// Formulaire marchand"
create_file "features/partner-onboarding/components/CourierOnboardingForm.tsx"  "// Formulaire livreur"
create_file "features/partner-onboarding/components/DocumentUpload.tsx"         "// Upload documents"
create_file "features/partner-onboarding/components/OnboardingStatus.tsx"       "// Suivi validation"
create_file "features/partner-onboarding/hooks/usePartnerOnboarding.ts"         "// Hook onboarding"
create_file "features/partner-onboarding/hooks/useDocumentVerification.ts"      "// Hook vérification documents"
create_file "features/partner-onboarding/services/partner.api.ts"               "// API partenaires"
create_file "features/partner-onboarding/types/partner.types.ts"                "// Types partenaires"

echo "✅ Arborescence des features créée avec succès !"
